// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type Usuario struct {
	ID           string  `json:"id"`
	NameLastName *string `json:"nameLastName,omitempty"`
	Username     *string `json:"username,omitempty"`
	Email        *string `json:"email,omitempty"`
	Role         *string `json:"role,omitempty"`
}
